import Head from "next/head";
import Image from "next/image";
import Main from "../Components/main/Main";
import Tender from "../Components/tender/Tender";
import Footer from "../Components/footer/footer";
import style  from "../Components/main/Main.module.css"
import { FaInstagramSquare, FaFacebook, FaWhatsapp} from "react-icons/fa";
export default function Home() {
  return (
    <>
      <Head>
        <title> Create Next App </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
        <Tender />
        <Footer />
      </main>
      <footer></footer>{" "}
    </>
  );
}
