import Head from "next/head";
import Image from "next/image";
import Main from "../Components/main/Main";
import Tender from "../Components/tender/Tender";
import Footer from "../Components/footer/footer";
import style  from "../Components/main/Main.module.css"
import { FaInstagramSquare, FaFacebook, FaWhatsapp} from "react-icons/fa";
import Contact from "../Components/Contact/Contact";
import SimpleSlider from "../Components/slider";
import DemoCarousel from "../Components/slider";
import Slider from "../Components/slider/index"
export default function Home() {
  return (
    <>
      <Head>
        <title> American Hospital Baku  </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slider />
        {/* <Main /> */}
        {/* <Tender /> */}

        {/* <SimpleSlider /> */}

     
               <Footer />

               {/* <DemoCarousel /> */}
      </main>
      <footer></footer>{" "}
    </>
  );
}
